# Generated by Django 4.2.6 on 2023-10-06 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the type of question (e.g. Multiple Choice, Text, Rating)', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the survey', max_length=255)),
                ('start_date', models.DateField(help_text='Enter the start date of the survey')),
                ('end_date', models.DateField(help_text='Enter the end date of the survey')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Enter the text for the question')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='controllers.questiontype')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='controllers.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(help_text='Enter the text for this choice', max_length=255)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='controllers.form')),
            ],
        ),
    ]
