# Generated by Django 4.2.6 on 2023-10-13 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controllers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('question_text', models.TextField(help_text='Enter the text for the question')),
            ],
        ),
        migrations.CreateModel(
            name='FormInputChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(help_text='Enter the text for this choice', max_length=255, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='controllers.forminput')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyOwners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyParticipantAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_float', models.FloatField(null=True)),
                ('value_int', models.IntegerField(null=True)),
                ('value_text', models.TextField(null=True)),
                ('choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answerscheckbox', to='controllers.forminputchoice')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_crypt', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the survey', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='form',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='form',
            name='survey',
        ),
        migrations.AddField(
            model_name='survey',
            name='salt',
            field=models.CharField(default='abc', help_text='abc', max_length=255),
        ),
        migrations.RenameModel(
            old_name='QuestionType',
            new_name='InputType',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.AddField(
            model_name='surveyparticipants',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controllers.survey'),
        ),
        migrations.AddField(
            model_name='surveyparticipantanswer',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controllers.surveyparticipants'),
        ),
        migrations.AddField(
            model_name='surveyowners',
            name='permissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controllers.surveypermissions'),
        ),
        migrations.AddField(
            model_name='surveyowners',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controllers.survey'),
        ),
        migrations.AddField(
            model_name='surveyowners',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forminput',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='controllers.inputtype'),
        ),
        migrations.AddField(
            model_name='forminput',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='controllers.survey'),
        ),
    ]
